name: Extract DNS

on:
  push:
    branches:
      - main

jobs:
  extract-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install distutils
        run: sudo apt-get install -y python3-distutils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install rdbtools

      - name: Parse redis_dns_v2.rdb and extract domains
        run: |
          python << EOF
          from rdbtools import RdbParser, MemoryCallback
          import re

          class DNSCallback(MemoryCallback):
              def __init__(self):
                  super().__init__()
                  self.domains = set()

              def set(self, key, value, expiry, info):
                  if isinstance(value, bytes):
                      value = value.decode('utf-8')
                  domains = re.findall(r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}', value)
                  self.domains.update(domains)

          callback = DNSCallback()
          parser = RdbParser(callback)
          with open('output/redis_dns_v2.rdb', 'rb') as rdb_file:
              parser.parse(rdb_file)

          with open('rule/dns_rules.txt', 'w') as output_file:
              output_file.write("\\n".join(sorted(callback.domains)))
          EOF

      - name: Output DNS Rules
        run: cat rule/dns_rules.txt
